version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taskmanagement-db
    environment:
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanagement-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanagement-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/taskmanagement
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      AI_SERVICE_URL: http://ai-service:8001
      UPLOAD_PATH: ./uploads
      MAX_FILE_SIZE: 5242880
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskmanagement-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # AI Service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: taskmanagement-ai
    environment:
      PORT: 8001
      ENVIRONMENT: production
      MODEL_CACHE_DIR: ./models
      MAX_SUMMARY_LENGTH: 150
      LOG_LEVEL: INFO
    ports:
      - "8001:8001"
    volumes:
      - ai_models:/app/models
    networks:
      - taskmanagement-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend (for development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanagement-frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
      VITE_AI_SERVICE_URL: http://localhost:8001
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ai-service
    networks:
      - taskmanagement-network

volumes:
  postgres_data:
  backend_uploads:
  ai_models:

networks:
  taskmanagement-network:
    driver: bridge
